services:
  # Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cache Redis
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # API Flask
  flask-api:
    build: .
    container_name: flask-api
    restart: always
    env_file:
      - .env
    # Executa o Flask apontando para o run.py e abrindo a porta para a rede externa
    command: python -m flask --app app run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
