version: "3.9"

services:

  db:
    image: postgres:15
    container_name: censo_db
    restart: always
    environment:
      POSTGRES_DB: censo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: censo_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/censo
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data: